name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  # Menjalankan sinkronisasi secara manual
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://rizkimauln:$HF_TOKEN@huggingface.co/spaces/rizkimauln/kompresijpegservice main --force
